load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "utils",
    srcs = [
        "gid.go",
        "signal.go",
    ],
    importpath = "liquid.io/go/pkg/utils",
    visibility = ["//visibility:public"],
    deps = [],
)
