cc_library(
    name = "libbtree",
    srcs = ["btree.cc"],
    hdrs = [
        "btree.h",
        "iterator.h",
        "node.h",
        "pagemanager.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
